const exSchoolsScholasticAchievements = [
    {
      std_id: "111",
      primary_school: {
        phase: {
          col1: null,
          col2: null,
          col3: null,
          col4: null,
          col5: null,
          col6: null,
          col7: null,
          col8: null,
          col9: null,
          col10: null,
          col11: null,
        },
        year_and_month: {
          col1: "1995",
          col2: null,
          col3: null,
          col4: null,
          col5: null,
          col6: null,
          col7: null,
          col8: null,
          col9: null,
          col10: null,
          col11: null,
        },
        grade: {
          col1: "2",
          col2: null,
          col3: null,
          col4: null,
          col5: null,
          col6: null,
          col7: null,
          col8: null,
          col9: null,
          col10: null,
          col11: null,
        },
        level_of_grade: {
          col1: "b",
          col2: null,
          col3: null,
          col4: null,
          col5: null,
          col6: null,
          col7: null,
          col8: null,
          col9: null,
          col10: null,
          col11: null,
        },
        english_home: {
          col1: "Y",
          col2: null,
          col3: null,
          col4: null,
          col5: null,
          col6: null,
          col7: null,
          col8: null,
          col9: null,
          col10: null,
          col11: null,
        },
  
        subjects: [
          {
            id: "mn",
            name: "Mathematics",
            cols: {
              col1: "90",
              col2: null,
              col3: null,
              col4: null,
              col5: null,
              col6: null,
              col7: null,
              col8: null,
              col9: null,
              col10: null,
              col11: null,
            },
          },
        ],
  
        average_symbol_learner: {
          col1: "    90",
          col2: null,
          col3: null,
          col4: null,
          col5: null,
          col6: null,
          col7: null,
          col8: null,
          col9: null,
          col10: null,
          col11: null,
        },
        average_symbol_grade: {
          col1: "A",
          col2: null,
          col3: null,
          col4: null,
          col5: null,
          col6: null,
          col7: null,
          col8: null,
          col9: null,
          col10: null,
          col11: null,
        },
        pass_fail: {
          col1: "P",
          col2: null,
          col3: null,
          col4: null,
          col5: null,
          col6: null,
          col7: null,
          col8: null,
          col9: null,
          col10: null,
          col11: null,
        },
        school_attendence: {
          col1: "G",
          col2: null,
          col3: null,
          col4: null,
          col5: null,
          col6: null,
          col7: null,
          col8: null,
          col9: null,
          col10: null,
          col11: null,
        },
        attendence_grading: {
          col1: null,
          col2: null,
          col3: null,
          col4: null,
          col5: null,
          col6: null,
          col7: null,
          col8: null,
          col9: null,
          col10: null,
          col11: null,
        },
      },
  
      secondary_school: {
        phase: {
          col1: null,
          col2: null,
          col3: null,
          col4: null,
          col5: null,
          col6: null,
          col7: null,
          col8: null,
          col9: null,
          col10: null,
          col11: null,
        },
        year_and_month: {
          col1: null,
          col2: null,
          col3: null,
          col4: null,
          col5: null,
          col6: null,
          col7: null,
          col8: null,
          col9: null,
          col10: null,
          col11: null,
        },
        grade: {
          col1: null,
          col2: null,
          col3: null,
          col4: null,
          col5: null,
          col6: null,
          col7: null,
          col8: "11",
          col9: "11",
          col10: "12",
          col11: "12",
        },
        level_of_grade: {
          col1: null,
          col2: null,
          col3: null,
          col4: null,
          col5: null,
          col6: null,
          col7: null,
          col8: null,
          H: "I",
          col10: "H",
          col11: "I",
        },
        english_home: {
          col1: null,
          col2: null,
          col3: null,
          col4: null,
          col5: null,
          col6: null,
          col7: null,
          col8: null,
          col9: null,
          col10: null,
          col11: null,
        },
  
        subjects: [
          {
            id: null,
            name: null,
            cols: {
              col1: null,
              col2: null,
              col3: null,
              col4: null,
              col5: null,
              col6: null,
              col7: null,
              col8: null,
              col9: null,
              col10: null,
              col11: null,
            },
          },
        ],
  
        average_symbol_learner: {
          col1: null,
          col2: null,
          col3: null,
          col4: null,
          col5: null,
          col6: null,
          col7: null,
          col8: null,
          col9: null,
          col10: null,
          col11: null,
        },
        average_symbol_grade: {
          col1: null,
          col2: null,
          col3: null,
          col4: null,
          col5: null,
          col6: null,
          col7: null,
          col8: null,
          col9: null,
          col10: null,
          col11: null,
        },
        pass_fail: {
          col1: null,
          col2: null,
          col3: null,
          col4: null,
          col5: null,
          col6: null,
          col7: null,
          col8: null,
          col9: null,
          col10: null,
          col11: null,
        },
        school_attendence: {
          col1: null,
          col2: null,
          col3: null,
          col4: null,
          col5: null,
          col6: null,
          col7: null,
          col8: null,
          col9: null,
          col10: null,
          col11: null,
        },
        attendence_grading: {
          col1: null,
          col2: null,
          col3: null,
          col4: null,
          col5: null,
          col6: null,
          col7: null,
          col8: null,
          col9: null,
          col10: null,
          col11: null,
        },
      },
    },
    {
      std_id: "222",
      primary_school: {
        phase: {
          col1: null,
          col2: null,
          col3: null,
          col4: null,
          col5: null,
          col6: null,
          col7: null,
          col8: null,
          col9: null,
          col10: null,
          col11: null,
        },
        year_and_month: {
          col1: "1995",
          col2: null,
          col3: null,
          col4: null,
          col5: null,
          col6: null,
          col7: null,
          col8: null,
          col9: null,
          col10: null,
          col11: null,
        },
        grade: {
          col1: "2",
          col2: null,
          col3: null,
          col4: null,
          col5: null,
          col6: null,
          col7: null,
          col8: null,
          col9: null,
          col10: null,
          col11: null,
        },
        level_of_grade: {
          col1: "b",
          col2: null,
          col3: null,
          col4: null,
          col5: null,
          col6: null,
          col7: null,
          col8: null,
          col9: null,
          col10: null,
          col11: null,
        },
        english_home: {
          col1: "Y",
          col2: null,
          col3: null,
          col4: null,
          col5: null,
          col6: null,
          col7: null,
          col8: null,
          col9: null,
          col10: null,
          col11: null,
        },
  
        subjects: [
          {
            id: "mn",
            name: "Mathematics",
            cols: {
              col1: "90",
              col2: null,
              col3: null,
              col4: null,
              col5: null,
              col6: null,
              col7: null,
              col8: null,
              col9: null,
              col10: null,
              col11: null,
            },
          },
        ],
  
        average_symbol_learner: {
          col1: "    90",
          col2: null,
          col3: null,
          col4: null,
          col5: null,
          col6: null,
          col7: null,
          col8: null,
          col9: null,
          col10: null,
          col11: null,
        },
        average_symbol_grade: {
          col1: "A",
          col2: null,
          col3: null,
          col4: null,
          col5: null,
          col6: null,
          col7: null,
          col8: null,
          col9: null,
          col10: null,
          col11: null,
        },
        pass_fail: {
          col1: "P",
          col2: null,
          col3: null,
          col4: null,
          col5: null,
          col6: null,
          col7: null,
          col8: null,
          col9: null,
          col10: null,
          col11: null,
        },
        school_attendence: {
          col1: "G",
          col2: null,
          col3: null,
          col4: null,
          col5: null,
          col6: null,
          col7: null,
          col8: null,
          col9: null,
          col10: null,
          col11: null,
        },
        attendence_grading: {
          col1: null,
          col2: null,
          col3: null,
          col4: null,
          col5: null,
          col6: null,
          col7: null,
          col8: null,
          col9: null,
          col10: null,
          col11: null,
        },
      },
  
      secondary_school: {
        phase: {
          col1: null,
          col2: null,
          col3: null,
          col4: null,
          col5: null,
          col6: null,
          col7: null,
          col8: null,
          col9: null,
          col10: null,
          col11: null,
        },
        year_and_month: {
          col1: null,
          col2: null,
          col3: null,
          col4: null,
          col5: null,
          col6: null,
          col7: null,
          col8: null,
          col9: null,
          col10: null,
          col11: null,
        },
        grade: {
          col1: null,
          col2: null,
          col3: null,
          col4: null,
          col5: null,
          col6: null,
          col7: null,
          col8: "11",
          col9: "11",
          col10: "12",
          col11: "12",
        },
        level_of_grade: {
          col1: null,
          col2: null,
          col3: null,
          col4: null,
          col5: null,
          col6: null,
          col7: null,
          col8: null,
          H: "I",
          col10: "H",
          col11: "I",
        },
        english_home: {
          col1: null,
          col2: null,
          col3: null,
          col4: null,
          col5: null,
          col6: null,
          col7: null,
          col8: null,
          col9: null,
          col10: null,
          col11: null,
        },
  
        subjects: [
          {
            id: null,
            name: null,
            cols: {
              col1: null,
              col2: null,
              col3: null,
              col4: null,
              col5: null,
              col6: null,
              col7: null,
              col8: null,
              col9: null,
              col10: null,
              col11: null,
            },
          },
        ],
  
        average_symbol_learner: {
          col1: null,
          col2: null,
          col3: null,
          col4: null,
          col5: null,
          col6: null,
          col7: null,
          col8: null,
          col9: null,
          col10: null,
          col11: null,
        },
        average_symbol_grade: {
          col1: null,
          col2: null,
          col3: null,
          col4: null,
          col5: null,
          col6: null,
          col7: null,
          col8: null,
          col9: null,
          col10: null,
          col11: null,
        },
        pass_fail: {
          col1: null,
          col2: null,
          col3: null,
          col4: null,
          col5: null,
          col6: null,
          col7: null,
          col8: null,
          col9: null,
          col10: null,
          col11: null,
        },
        school_attendence: {
          col1: null,
          col2: null,
          col3: null,
          col4: null,
          col5: null,
          col6: null,
          col7: null,
          col8: null,
          col9: null,
          col10: null,
          col11: null,
        },
        attendence_grading: {
          col1: null,
          col2: null,
          col3: null,
          col4: null,
          col5: null,
          col6: null,
          col7: null,
          col8: null,
          col9: null,
          col10: null,
          col11: null,
        },
      },
    },
    {
      std_id: "333",
      primary_school: {
        phase: {
          col1: null,
          col2: null,
          col3: null,
          col4: null,
          col5: null,
          col6: null,
          col7: null,
          col8: null,
          col9: null,
          col10: null,
          col11: null,
        },
        year_and_month: {
          col1: "1995",
          col2: null,
          col3: null,
          col4: null,
          col5: null,
          col6: null,
          col7: null,
          col8: null,
          col9: null,
          col10: null,
          col11: null,
        },
        grade: {
          col1: "2",
          col2: null,
          col3: null,
          col4: null,
          col5: null,
          col6: null,
          col7: null,
          col8: null,
          col9: null,
          col10: null,
          col11: null,
        },
        level_of_grade: {
          col1: "b",
          col2: null,
          col3: null,
          col4: null,
          col5: null,
          col6: null,
          col7: null,
          col8: null,
          col9: null,
          col10: null,
          col11: null,
        },
        english_home: {
          col1: "Y",
          col2: null,
          col3: null,
          col4: null,
          col5: null,
          col6: null,
          col7: null,
          col8: null,
          col9: null,
          col10: null,
          col11: null,
        },
  
        subjects: [
          {
            id: "mn",
            name: "Mathematics",
            cols: {
              col1: "90",
              col2: null,
              col3: null,
              col4: null,
              col5: null,
              col6: null,
              col7: null,
              col8: null,
              col9: null,
              col10: null,
              col11: null,
            },
          },
        ],
  
        average_symbol_learner: {
          col1: "    90",
          col2: null,
          col3: null,
          col4: null,
          col5: null,
          col6: null,
          col7: null,
          col8: null,
          col9: null,
          col10: null,
          col11: null,
        },
        average_symbol_grade: {
          col1: "A",
          col2: null,
          col3: null,
          col4: null,
          col5: null,
          col6: null,
          col7: null,
          col8: null,
          col9: null,
          col10: null,
          col11: null,
        },
        pass_fail: {
          col1: "P",
          col2: null,
          col3: null,
          col4: null,
          col5: null,
          col6: null,
          col7: null,
          col8: null,
          col9: null,
          col10: null,
          col11: null,
        },
        school_attendence: {
          col1: "G",
          col2: null,
          col3: null,
          col4: null,
          col5: null,
          col6: null,
          col7: null,
          col8: null,
          col9: null,
          col10: null,
          col11: null,
        },
        attendence_grading: {
          col1: null,
          col2: null,
          col3: null,
          col4: null,
          col5: null,
          col6: null,
          col7: null,
          col8: null,
          col9: null,
          col10: null,
          col11: null,
        },
      },
  
      secondary_school: {
        phase: {
          col1: null,
          col2: null,
          col3: null,
          col4: null,
          col5: null,
          col6: null,
          col7: null,
          col8: null,
          col9: null,
          col10: null,
          col11: null,
        },
        year_and_month: {
          col1: null,
          col2: null,
          col3: null,
          col4: null,
          col5: null,
          col6: null,
          col7: null,
          col8: null,
          col9: null,
          col10: null,
          col11: null,
        },
        grade: {
          col1: null,
          col2: null,
          col3: null,
          col4: null,
          col5: null,
          col6: null,
          col7: null,
          col8: "11",
          col9: "11",
          col10: "12",
          col11: "12",
        },
        level_of_grade: {
          col1: null,
          col2: null,
          col3: null,
          col4: null,
          col5: null,
          col6: null,
          col7: null,
          col8: null,
          H: "I",
          col10: "H",
          col11: "I",
        },
        english_home: {
          col1: null,
          col2: null,
          col3: null,
          col4: null,
          col5: null,
          col6: null,
          col7: null,
          col8: null,
          col9: null,
          col10: null,
          col11: null,
        },
  
        subjects: [
          {
            id: null,
            name: null,
            cols: {
              col1: null,
              col2: null,
              col3: null,
              col4: null,
              col5: null,
              col6: null,
              col7: null,
              col8: null,
              col9: null,
              col10: null,
              col11: null,
            },
          },
        ],
  
        average_symbol_learner: {
          col1: null,
          col2: null,
          col3: null,
          col4: null,
          col5: null,
          col6: null,
          col7: null,
          col8: null,
          col9: null,
          col10: null,
          col11: null,
        },
        average_symbol_grade: {
          col1: null,
          col2: null,
          col3: null,
          col4: null,
          col5: null,
          col6: null,
          col7: null,
          col8: null,
          col9: null,
          col10: null,
          col11: null,
        },
        pass_fail: {
          col1: null,
          col2: null,
          col3: null,
          col4: null,
          col5: null,
          col6: null,
          col7: null,
          col8: null,
          col9: null,
          col10: null,
          col11: null,
        },
        school_attendence: {
          col1: null,
          col2: null,
          col3: null,
          col4: null,
          col5: null,
          col6: null,
          col7: null,
          col8: null,
          col9: null,
          col10: null,
          col11: null,
        },
        attendence_grading: {
          col1: null,
          col2: null,
          col3: null,
          col4: null,
          col5: null,
          col6: null,
          col7: null,
          col8: null,
          col9: null,
          col10: null,
          col11: null,
        },
      },
    },
  ];
  
  const exScholasticAchievementsReducer = (
    state = exSchoolsScholasticAchievements,
    action
  ) => {
    return state;
  };
  
  export default exScholasticAchievementsReducer;
  